# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cebd719b325e2c6d671598a9f7f64b928ccafbe2c73a88fc6713f1df25f800f03c700b1d82d02ddc308f430dc46f8827950c9de56340830a0be744328e3656e

test:
  secret_key_base: 0495b3bb035bc484c7b2fe88e4081fdbd8df30d35570eae9f207a1b39efa4daef75de1190575f473767639fb851b9a9fef1843ee1466ad0c882e313a3c133540

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
